###
POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
    "username":"huan",
    "password":"Kelkifa123",
    "fullname":"Pham Long Huan"
}



###
GET http://localhost:8080/api/food/json?s=Cà

###

GET http://localhost:8080/api/food/custom


###
GET http://localhost:8080/api/food/json?discount=desc



### cart get
GET http://localhost:8080/api/cart/get



### cart add
POST http://localhost:8080/api/cart/add
Content-Type: application/json

{
    "userId":"61b3138a6e0c8e00233e75ee",
    "food":"61aec754db181d00237c9883",
    "soLuong":"2"
}

### remove cart

POST http://localhost:8080/api/cart/remove


### order create
POST http://localhost:8080/api/order/create
Content-Type: application/json

{
    "userId":"61b8b5a8ab4af30023b7a048",
    "cartIdListJson":"[]"
}

